receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"
exporters:
  debug:

  #logging:
    #verbosity: detailed
    
  #traces
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

  #metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    #tls:
      #insecure: true 
      #ca_file: "/path/to/ca.pem"
      #cert_file: "/path/to/cert.pem"
      #key_file: "/path/to/key.pem"
    namespace: test-space
    #const_labels:
      #label1: value1
      #"another label": spaced value
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true

  #traces
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
  #logs  
  otlphttp/loki:
    auth:
      authenticator: basicauth/loki
    endpoint: http://loki:3100/otlp
    
  #currently traces and logs  
  elasticsearch:
    endpoint: http://elasticsearch:9200
    auth:
      authenticator: basicauth
 
processors:
  batch:
  
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  basicauth/loki:
    client_auth:
      username: loki
      password: loki
  basicauth:
    client_auth:
      username: elastic
      password: changeme
service:
  extensions: [pprof, zpages, health_check, basicauth/loki,basicauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,zipkin,otlp,elasticsearch]
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/loki,elasticsearch]
