receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"
exporters:
  logging:
    verbosity: detailed
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging,zipkin]
    logs:
      receivers: [otlp]
      exporters: [logging]
