receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"
exporters:
  debug:

  #logging:
    #verbosity: detailed
    
  #traces
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

  #metrics
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true

  #traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  #traces
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  #logs  
  otlphttp/loki:
    auth:
      authenticator: basicauth/loki
    endpoint: http://loki:3100/otlp
    
  #currently traces and logs  
  elasticsearch:
    endpoint: http://elasticsearch:9200
    sending_queue:
      enabled: true
      queue_size: 1000
    auth:
      authenticator: basicauth
 
processors:
  batch:
  
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  basicauth/loki:
    client_auth:
      username: loki
      password: loki
  basicauth:
    client_auth:
      username: elastic
      password: changeme
service:
  extensions: [pprof, zpages, health_check, basicauth/loki,basicauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlphttp/prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,zipkin,otlp/jaeger,otlp/tempo,elasticsearch]
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/loki,elasticsearch]
  telemetry:
    metrics:
      level: detailed
      readers:
        - periodic:
            interval: 10000
            timeout: 5000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: collector:4318
