apiVersion: 1

datasources:
  - name: Elastic
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    editable: true
    basicAuth: true
    basicAuthUser: elastic
    jsonData:
      #index: '[metrics-]YYYY.MM.DD'
      #interval: Daily
      timeField: '@timestamp'
    secureJsonData:
      basicAuthPassword: changeme